FROM openjdk:17-alpine
WORKDIR usr/src
ADD /target/booking-0.0.1-SNAPSHOT.jar /usr/src/booking-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","booking-0.0.1-SNAPSHOT.jar"]
ENV MONGOURL=mongodb://mongos:27017/HealthcareDB
ENV EUREKAURL=http://eurekaservice:8761/eureka