FROM openjdk:17-alpine
WORKDIR usr/src
ADD /target/SampleEurekaServer-0.0.1-SNAPSHOT.jar /usr/src/SampleEurekaServer-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","SampleEurekaServer-0.0.1-SNAPSHOT.jar"]