version: '3.4'

services:
   db:
     image: mysql:8.0.32
     environment: 
        MYSQL_ROOT_PASSWORD: password         
        MYSQL_DATABASE: review  
     restart: always
     container_name: db-review         
       
     ports:
       - 3305:3306               

   reviewsservice:
     depends_on:
       - db
     image: ${DOCKER_REGISTRY-}reviews
     restart: on-failure
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - "9020:80"

volumes:
   dbdata:

