FROM openjdk:17-alpine 
WORKDIR usr/src
ADD /target/medication-0.0.1-SNAPSHOT.jar /usr/src/medication-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "medication-0.0.1-SNAPSHOT.jar"]
ENV MONGOURL=mongodb://mongos:27017/medications
ENV EUREKAURL=http://eurekaservice:8761/eureka