FROM openjdk:17-alpine
WORKDIR usr/src
ADD /target/Authentication-0.0.1-SNAPSHOT.jar /usr/src/Authentication-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Authentication-0.0.1-SNAPSHOT.jar"]
ENV MYSQLURL=jdbc:mysql://mysqls:3306/HealthcareDB?createDatabaseIfNotExist=true&user=root&password=rootpassword
ENV EUREKAURL=http://eurekaservice:8761/eureka