app:
  message: Successfuly sent the message to client
  
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    exchange: cgipharamexchange
    queue: cgiqueue
    routingkey: cgipharamaroutekey
      
server:
  port: 9090